package by.siegell.caliper.reporter

import by.siegell.caliper.domain.CaliperClassInfo
import by.siegell.caliper.reporter.mapper.MdMapper
import by.siegell.caliper.reporter.mapper.MermaidMapper
import by.siegell.caliper.reporter.section.ClassSection
import by.siegell.caliper.reporter.section.MermaidSection

class MarkdownReporter {

    private val sections = listOf(
        ClassSection(MdMapper()),
        MermaidSection(MermaidMapper())
    )

    fun generateReport(classes: List<CaliperClassInfo>): ByteArray {
        return buildString {
            appendLine("# Caliper report\n")
            classes.forEach { info ->
                appendLine("---")
                sections.forEach { it.append(this, info) }
                appendLine("---")
            }
            appendLine("\n\nGenerated by CaliperProcessor!")
        }.toByteArray()
    }


}