package by.siegell.caliper.processor

import by.siegell.caliper.parser.Parser
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import java.nio.file.Paths

class CaliperProcessor(
    private val environment: SymbolProcessorEnvironment,
    private val parser: Parser
) : SymbolProcessor {

    private var isFirstRound = true

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (!isFirstRound) return emptyList()
        isFirstRound = false

        environment.logger.info("CaliperProcessor starting!")

        val oldReport = Paths.get("build/generated/ksp/main/resources/caliper/report.md").toFile()
        if (oldReport.exists()) oldReport.delete()

        environment.codeGenerator.createNewFile(
            dependencies = Dependencies(false),
            packageName = "caliper",
            fileName = "report",
            extensionName = "md"
        ).use { fileOutput ->
            val symbols = resolver.getSymbolsWithAnnotation("by.siegell.caliper.domain.CaliperTarget")
            val content = buildString {
                appendLine("# Caliper report\n")
                symbols.filterIsInstance<KSClassDeclaration>()
                    .forEach { ksClass ->
                        val info = parser.analyzeClass(ksClass)
                        appendLine("---")
                        appendLine("## ${info.name}")
                        appendLine("from package: ${info.packageName}")
                        appendLine("### properties")
                        info.properties.forEach { property ->
                            appendLine("- `${property.name}` : ${property.type}")
                        }
                        appendLine("### functions")
                        info.functions.forEach { function ->
                            appendLine("- fun `${function.name}` (${function.parameters.joinToString { "`${it.name}` : ${it.type}" }}) : ${function.returnType}")
                        }
                        appendLine("---")
                    }
                appendLine("\n\nGenerated by CaliperProcessor!")
            }
            fileOutput.write(content.toByteArray())
        }

        environment.logger.info("CaliperProcessor ended!")
        return emptyList()
    }
}